//企业用户
var qy_data = [
               {
            	   id:"1",
            	   name:"化石燃料固定燃烧源/工艺过程源",
            	   value:[{
            		   id:1,value:"煤炭开采和洗选业"
            	   },{
            		   id:2,value:"石油和天然气开采业"
            	   },{
            		   id:3,value:"黑色金属矿采选业"
            	   },{
            		   id:4,value:"有色金属矿采选业"
            	   },{
            		   id:5,value:"非金属矿采选业"
            	   },{
            		   id:6,value:"开采辅助活动"
            	   },{
            		   id:7,value:"其它采矿业"
            	   },{
            		   id:8,value:"农副食品加工业"
            	   },{
            		   id:9,value:"食品制造业"
            	   },{
            		   id:10,value:"酒、饮料和精制茶制造业"
            	   },{
            		   id:11,value:"烟草制品业"
            	   },{
            		   id:12,value:"纺织业"
            	   },{
            		   id:13,value:"纺织服装、服饰业"
            	   },{
            		   id:14,value:"皮革、毛皮、羽毛及其制品和制鞋业"
            	   },{
            		   id:15,value:"木材加工和木、竹、藤、棕、草制品业"
            	   },{
            		   id:16,value:"家具制造业"
            	   },{
            		   id:17,value:"造纸和纸制品业"
            	   },{
            		   id:18,value:"印刷和记录媒介复制业"
            	   },{
            		   id:19,value:"文教、工美、体育和娱乐用品制造业"
            	   },{
            		   id:20,value:"石油加工、炼焦和核燃料加工业"
            	   },{
            		   id:21,value:"化学原料和化学制品制造业"
            	   },{
            		   id:22,value:"医药制造业"
            	   },{
            		   id:23,value:"化学纤维制造业"
            	   },{
            		   id:24,value:"橡胶和塑料制品业"
            	   },{
            		   id:25,value:"非金属矿物制品业"
            	   },{
            		   id:26,value:"黑色金属冶炼和压延加工业"
            	   },{
            		   id:27,value:"有色金属冶炼和压延加工业"
            	   },{
            		   id:28,value:"金属制品业"
            	   },{
            		   id:29,value:"通用设备制造业"
            	   },{
            		   id:30,value:"专用设备制造业"
            	   },{
            		   id:31,value:"汽车制造业"
            	   },{
            		   id:32,value:"铁路、船舶、航空航天和其它运输设备制造业"
            	   },{
            		   id:33,value:"电气机械和器材制造业"
            	   },{
            		   id:34,value:"计算机、通信和其它电子设备制造业"
            	   },{
            		   id:35,value:"仪器仪表制造业"
            	   },{
            		   id:36,value:"其它制造业"
            	   },{
            		   id:37,value:"废弃资源综合利用业"
            	   },{
            		   id:38,value:"金属制品、机械和设备修理业"
            	   },{
            		   id:39,value:"电力生产"
            	   },{
            		   id:40,value:"电力供应"
            	   },{
            		   id:41,value:"工业热力生产和供应"
            	   },{
            		   id:42,value:"民用热力生产和供应"
            	   },{
            		   id:43,value:"燃气生产和供应业"
            	   }
            	   ]
               },{
            	   id:"3",
            	   name:"移动源",
            	   value:[
            	          {
            	        	  id:44,value:"民航飞机"
            	          }
            	          ]
               },{
            	   id:"4",
            	   name:"溶剂使用源",
            	   value:[
            	          {
            	        	  id:45,value:"印刷印染"
            	          },{
            	        	  id:46,value:"工业喷涂"
            	          },{
            	        	  id:47,value:"其它溶剂使用"
            	          }
            	          ]
               },{
            	   id:"5",
            	   name:"农业源",
            	   value:[
            	          {
            	        	  id:48,value:"畜禽养殖"
            	          }
            	          ]
               },{
            	   id:"6",
            	   name:"扬尘源",
            	   value:[
            	          {
            	        	  id:49,value:"施工扬尘"
            	          },{
            	        	  id:50,value:"堆场扬尘"
            	          }
            	          ]

               },{
            	   id:"8",
            	   name:"生物质燃烧源",
            	   value:[
            	          {
            	        	  id:51,value:"生物质燃料"
            	          }
            	          ]
               },{
            	   id:"7",
            	   name:"储存运输",
            	   value:[
            	          {
            	        	  id:52,value:"油气储运"
            	          }
            	          ]
               },{
            	   id:"9",
            	   name:"废弃物处理源",
            	   value:[
            	          {
            	        	  id:53,value:"废水处理"
            	          },{
            	        	  id:54,value:"固废处理"
            	          },{
            	        	  id:55,value:"烟气脱硝"
            	          }
            	          ]
               },{
            	   id:"10",
            	   name:"其它排放源",
            	   value:[
            	          {
            	        	  id:56,value:"餐饮油烟"
            	          }
            	          ]
               },{
            	   id:"11",
            	   name:"其它",
            	   value:[
            	          {
            	        	  id:"-1",value:"其他"
            	          }
            	          ]
               }
               ];
//市级填报用户
var sj_data = [
               {
            	   id:"1",
            	   name:"化石燃料固定燃烧源",
            	   value:[
            	          {
            	        	  id:11,value:"电力",name:[]
            	          },{
            	        	  id:12,value:"工业锅炉",name:[]
            	          },{
            	        	  id:13,value:"民用源",name:[]
            	          }
            	          ]
               },{
            	   id:"2",
            	   name:"工艺过程源",
            	   value:[
            	          {
            	        	  id:14,value:"玻璃",name:[]
            	          },{
            	        	  id:15,value:"独立焦化",name:[]
            	          },{
            	        	  id:16,value:"钢铁",name:[]
            	          },{
            	        	  id:17,value:"化工化纤",name:[]
            	          },{
            	        	  id:18,value:"水泥",name:[]
            	          },{
            	        	  id:19,value:"其它工业企业",name:[]
            	          }
            	          ]
               },{
            	   id:"3",
            	   name:"移动源",
            	   value:[
            	          {
            	        	  id:20,value:"机动车",name:[]
            	          },{
            	        	  id:21,value:"飞机",name:[]
            	          },{
            	        	  id:22,value:"船舶",name:[]
            	          },{
            	        	  id:23,value:"非道移机械",name:[]
            	          }
            	          ]
               },{
            	   id:"4",
            	   name:"溶剂使用源",
            	   value:[
            	          {
            	        	  id:24,value:"工业喷涂",name:[]
            	          },{
            	        	  id:25,value:"建筑涂料",name:[]
            	          },{
            	        	  id:26,value:"印刷印染",name:[]
            	          },{
            	        	  id:27,value:"农药使用",name:[]
            	          },{
            	        	  id:28,value:"其它溶剂使用",name:[]
            	          }
            	          ]
               },{
            	   id:"5",
            	   name:"农业源",
            	   value:[
            	          {
            	        	  id:29,value:"氮肥施用",name:[]
            	          },{
            	        	  id:30,value:"固氮植物",name:[]
            	          },{
            	        	  id:31,value:"秸秆堆肥",name:[]
            	          },{
            	        	  id:32,value:"人体粪便",name:[]
            	          },{
            	        	  id:33,value:"畜禽养殖",name:[]
            	          },{
            	        	  id:34,value:"土壤本底",name:[]
            	          }
            	          ]
               },{
            	   id:"6",
            	   name:"扬尘源",
            	   value:[
            	          {
            	        	  id:35,value:"道路扬尘",name:[]
            	          },{
            	        	  id:36,value:"堆场扬尘",name:[]
            	          },{
            	        	  id:37,value:"施工扬尘",name:[]
            	          },{
            	        	  id:38,value:"土壤扬尘",name:[]
            	          }
            	          ]
               },{
            	   id:"8",
            	   name:"储存运输",
            	   value:[
            	          {
            	        	  id:41,value:"油气输送",name:[]
            	          },{
            	        	  id:40,value:"油气储存",name:[]
            	          },{
            	        	  id:39,value:"加油站",name:[]
            	          }
            	          ]

               },{
            	   id:"7",
            	   name:"生物质燃烧源",
            	   value:[
            	          {
            	        	  id:42,value:"生物质燃料",name:[]
            	          },{
            	        	  id:43,value:"生物质开放燃烧",name:[]
            	          }
            	          ]
               },{
            	   id:"9",
            	   name:"废弃物处理源",
            	   value:[
            	          {
            	        	  id:44,value:"废水处理",name:[]
            	          },{
            	        	  id:45,value:"固废处理",name:[]
            	          },{
            	        	  id:46,value:"烟气脱硝",name:[]
            	          }
            	          ]
               },{
            	   id:"10",
            	   name:"其它排放源",
            	   value:[
            	          {
            	        	  id:47,value:"餐饮油烟",name:[]
            	          }
            	          ]
               }
               ];
var pfy={
		"化石燃料固定燃烧源":"1",
		"工艺过程源":"2",
  		"移动源":"3",
  		"溶剂使用源":"4",
  		"农业源":"5",
  		"扬尘源":"6",
  		"生物质燃烧源":"7",
		"储存运输源":"8",
  		"废弃物处理源":"9",
  		"其他排放源	":"10"
};